services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: event_analytics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c log_min_messages=PANIC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - app_network

  redis:
    image: redis:8.2.2-alpine3.22
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app_network

  api:
    container_name: events_api
    build:
      context: .
    env_file:
      - .env
#    command: uvicorn main:main_app --host 0.0.0.0 --port 5066 --workers 1
    command: >
      sh -c "
        if [ ! -d alembic ]; then
          alembic init alembic;
        fi &&
        alembic revision --autogenerate -m 'init' || true &&
        alembic upgrade head &&
        uvicorn main:main_app --host 0.0.0.0 --port 5066 --workers 1
      "
    ports:
      - "5066:5066"
    volumes:
      - ".:/app"
    depends_on:
      - pg
      - redis

    networks:
      - app_network

#  adminer:
#    image: adminer
#    ports:
#      - "8080:8080"
#
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: rmuraviov.dev@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    ports:
#      - "5050:80"

volumes:
  pgdata:

networks:
  app_network: