"""update  models

Revision ID: 2fc4883c28ec
Revises: 61b3ff6d486a
Create Date: 2025-10-24 23:35:21.719088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fc4883c28ec'
down_revision: Union[str, Sequence[str], None] = '61b3ff6d486a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('properties_json', sa.JSON(), nullable=True))
    op.drop_column('events', 'properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('events', 'properties_json')
    # ### end Alembic commands ###
